version: "3"
services:
  target:
    image: postgres
    environment:
      - POSTGRES_USER=target
      - POSTGRES_PASSWORD=target
      - POSTGRES_DB=target
    ports:
      - "5432:5432"
  symds_target:
    build:
      context: .
    environment:
      - HTTPS=FALSE
      - GROUP_ID=target
      - DB_HOST=target
      - DB_TYPE=postgres
      - DB_NAME=target
      - DB_USER=target
      - DB_PASS=target
      - SYNC_URL=http://symds_target:31415/sync/target
      - REGISTRATION_URL=http://symds_source:31415/sync/source
  symds_source:
    build:
      context: .
    environment:
      - HTTPS=FALSE
      - GROUP_ID=source
      - DB_HOST=source
      - DB_TYPE=postgres
      - DB_NAME=source
      - DB_USER=source
      - DB_PASS=source
      - SYNC_URL=http://symds_source:31415/sync/source
      - REPLICATE_TO=target
      - REPLICATE_TABLE=test
  source:
    build:
      context: postgres-source
    environment:
      - POSTGRES_USER=source
      - POSTGRES_PASSWORD=source
      - POSTGRES_DB=source
    ports:
      - "5431:5432"
