version: "3"
services:
  target:
    image: postgres
    environment:
      - POSTGRES_USER=target
      - POSTGRES_PASSWORD=target
      - POSTGRES_DB=target
    ports:
      - "5432:5432"
  symds_target:
    build:
      context: .
    environment:
      - HTTPS=TRUE
      - GROUP_ID=target
      - DB_HOST=target
      - DB_TYPE=postgres
      - DB_NAME=target
      - DB_USER=target
      - DB_PASS=target
      - USERNAME=user
      - PASSWORD=pass
      - SYNC_URL=https://symds_target:31417/sync/target
      - REGISTRATION_URL=https://symds_source:31417/sync/source
    ports:
      - "31425:31415"
      - "31427:31417"
  symds_source:
    build:
      context: .
    environment:
      - HTTPS=TRUE
      - GROUP_ID=source
      - DB_HOST=source
      - DB_TYPE=postgres
      - DB_NAME=source
      - DB_USER=source
      - DB_PASS=source
      - USERNAME=user
      - PASSWORD=pass
      - SYNC_URL=https://symds_source:31417/sync/source
      - REPLICATE_TO=target
      - REPLICATE_TABLE=test
    ports:
      - "31415:31415"
      - "31417:31417"
  source:
    build:
      context: postgres-source
    environment:
      - POSTGRES_USER=source
      - POSTGRES_PASSWORD=source
      - POSTGRES_DB=source
    ports:
      - "5431:5432"
